---
deployment:
  tasks:
    - export DEPLOYPATH=/home/revlcdaw/revled_found
    - /bin/cp -R revled.org/* $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp server.py $DEPLOYPATH
